name: 'Terraform'

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless of the OS
    defaults:
      run:
        shell: bash

    steps:
      # Step 1: Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        env:
          GOOGLE_OAUTH_ACCESS_TOKEN: ${{ secrets.GOOGLE_OAUTH_ACCESS_TOKEN }}
        run: |
          echo $GOOGLE_OAUTH_ACCESS_TOKEN | gcloud auth activate-service-account --key-file=-
          gcloud config set project cicd0626

      # Step 3: Install Terraform (specify version as needed)
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0  # Specify your required version here

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Plan Terraform execution
      - name: Terraform Plan
        run: terraform plan -input=false

      # Step 6: Apply Terraform configuration
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve -input=false
